name: Unit Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test
        env:
          ISSUER: ${{ secrets.OIDC_ISSUER}}
          CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID}}
          REDIRECT_URL: ${{ secrets.OIDC_REDIRECT_URL}}
          REDIRECT_SCHEME: ${{ secrets.OIDC_REDIRECT_SCHEME}}
        run: ./gradlew build test dokka
